{{- if .Values.serviceMonitor.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "radar-gateway.fullname" . }}-jmx-configmap
  labels:
{{ include "radar-gateway.labels" . | indent 4 }}
data:
  config.yml: |
    jmxUrl: service:jmx:rmi:///jndi/rmi://localhost:9010/jmxrmi
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    ssl: false
{{- end }}
