apiVersion: v1
kind: Service
metadata:
  name: {{ include "radar-gateway.fullname" . }}
  labels:
{{ include "radar-gateway.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.serviceMonitor.enabled }}
    - name: metrics
      port: 5556
      protocol: TCP
      targetPort: metrics
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "radar-gateway.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
