{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "radar-gateway.fullname" . }}
  labels:
{{ include "radar-gateway.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
{{ include "radar-gateway.labels" . | indent 6 }}
  endpoints:
  - port: metrics
    interval: 15s
{{- end -}}
