apiVersion: v1
kind: Secret
metadata:
  name: {{ template "radar-s3-connector.fullname" . }}
  labels:
{{ include "radar-s3-connector.labels" . | indent 4 }}
type: Opaque
data:
  {{ if .Values.cc.enabled -}}
  {{- $jaasConfig := print `org.apache.kafka.common.security.plain.PlainLoginModule required username="` .Values.cc.apiKey `" password="` .Values.cc.apiSecret `";` }}
  schemaRegistryCredential: {{ print .Values.cc.schemaRegistryApiKey ":" .Values.cc.schemaRegistryApiSecret | b64enc | quote }}
  kafkaSaslJaasConfig: {{ $jaasConfig | b64enc | quote }}
  {{- end }}
  {{- if and .Values.bucketAccessKey .Values.bucketSecretKey }}
  awsAccessKey: {{ .Values.bucketAccessKey | b64enc | quote }}
  awsSecretKey: {{ .Values.bucketSecretKey | b64enc | quote }}
  {{- end }}
