apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "catalog-server.fullname" . }}
  labels:
    app: {{ template "catalog-server.name" . }}
    chart: {{ template "catalog-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.yaml: |
    # Kafka
    kafka:
      {{- range $key, $value := .Values.kafkaProperties }}
      {{ $key | replace "_" "." }}: {{ $value }}
      {{- end }}
      {{- if .Values.cc.enabled }}
      bootstrap.servers: {{ .Values.cc.bootstrapServerurl }}
      security.protocol: SASL_SSL
      ssl.endpoint.identification.algorithm: https
      sasl.mechanism: PLAIN
      {{- end }}

    sources:
      {{- toYaml .Values.sources | nindent 6 }}

    schemas:
      {{- toYaml .Values.schemas | nindent 6 }}

    topics:
      {{- toYaml .Values.topics | nindent 6 }}
