chart-dirs:
  - charts
  - cp-helm-charts/charts
chart-repos:
  - radar=https://radar-base.github.io/radar-helm-charts
  - prometheus-community=https://prometheus-community.github.io/helm-charts
debug: true
#excluded-charts:
#  - common
remote: origin
namespace: default
