chart-dirs:
  - charts
  - cp-helm-charts/charts
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
  - velero=https://vmware-tanzu.github.io/helm-charts
check-version-increment: true
debug: true
remote: origin
validate-chart-schema: true
validate-maintainers: false
validate-yaml: true
