chart-dirs:
  - charts
  - cp-helm-charts/charts
chart-repos:
  - radar=https://radar-base.github.io/radar-helm-charts
  - prometheus-community=https://prometheus-community.github.io/helm-charts
target-branch: main
check-version-increment: true
debug: true
remote: origin
validate-chart-schema: true
validate-maintainers: false
validate-yaml: true
