apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "radar-integration.fullname" . }}
  labels:
{{ include "radar-integration.labels" . | indent 4 }}
data:
  radar.yml: |
    # ManagementPortal configuration
    management_portal:
      oauth_client_id: {{ .Values.oauth_client_id }} #OAuth2 clientId used by the webApp for making requests
      oauth_client_secret: {{ .Values.oauth_client_secret }} #OAuth2 client secret
      base_url: {{ .Values.managementportal_url }} #Base URL of the Management Portal

    # Set of supported projects
    projects:
      {{- range .Values.projects }}
      - redcap_info:
          url: {{ .redcap_info.url }} #URL pointing REDCap instance
          project_id: {{ .redcap_info.project_id }} #REDCap project identifier
          api_path: {{ .redcap_info.api_path }} # Redcap relative api path
          enrolment_event: {{ .redcap_info.enrolment_event }} #Unique identifier for the enrolment event
          integration_form: {{ .redcap_info.integration_form }} #Name of integration REDCap form
          token: {{ .redcap_info.token }} #REDCap API Token used to identify the REDCap user against the REDCap instance
          attributes:
            {{- range .redcap_info.attributes }}
            - field_name: {{ . }}
            {{- end }}
        mp_info:
          # Management Portal project identifier
          project_name: {{ .mp_info.project_name }} #
      {{ end -}}
