{{- if (include "radar-output.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "radar-output.fullname" . }}
  labels:
    app: {{ template "radar-output.name" . }}
    chart: {{ template "radar-output.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  sourceS3AccessToken: {{ .Values.source.s3.accessToken | b64enc | quote }}
  sourceS3SecretKey: {{ .Values.source.s3.secretKey | b64enc | quote }}
  targetS3AccessToken: {{ .Values.target.s3.accessToken | b64enc | quote }}
  targetS3SecretKey: {{ .Values.target.s3.secretKey | b64enc | quote }}

  sourceAzureUsername: {{ .Values.source.azure.username | b64enc | quote }}
  sourceAzurePassword: {{ .Values.source.azure.password | b64enc | quote }}
  sourceAzureAccountName: {{ .Values.source.azure.accountName | b64enc | quote }}
  sourceAzureAccountKey: {{ .Values.source.azure.accountKey | b64enc | quote }}
  sourceAzureSasToken: {{ .Values.source.azure.sasToken | b64enc | quote }}

  targetAzureUsername: {{ .Values.target.azure.username | b64enc | quote }}
  targetAzurePassword: {{ .Values.target.azure.password | b64enc | quote }}
  targetAzureAccountName: {{ .Values.target.azure.accountName | b64enc | quote }}
  targetAzureAccountKey: {{ .Values.target.azure.accountKey | b64enc | quote }}
  targetAzureSasToken: {{ .Values.target.azure.sasToken | b64enc | quote }}
{{- end -}}
