apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "management-portal.fullname" . }}
  labels:
{{ include "management-portal.labels" . | indent 4 }}
data:
  healthcheck.sh: |
    #!/bin/sh
    STATUS=$(curl -m 1 localhost:8080/managementportal/management/health)
    if ! (echo "$STATUS" | grep -Fq 'db":{"status":"UP'); then
      exit 1
    fi
