{{- if .Values.ingress_rate_limited.enabled -}}
{{- $fullName := include "management-portal.fullname" . -}}
{{- $paths := .Values.ingress_rate_limited.paths -}}
{{- $hosts := .Values.ingress_rate_limited.hosts -}}
{{- $svcPort := .Values.service.port -}}
{{- $pathType := .Values.ingress_rate_limited.pathType -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-rate-limited
  labels:
{{ include "management-portal.labels" . | indent 4 }}
  {{- with .Values.ingress_rate_limited.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress_rate_limited.ingressClassName | quote }}
{{- if .Values.ingress_rate_limited.tls }}
  tls:
    - hosts:
      {{- range $hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .Values.ingress_rate_limited.tls.secretName }}
{{- end }}
  rules:
  {{- range .Values.ingress_rate_limited.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          {{- range $paths }}
          - path: {{ . | quote }}
            {{- if and $pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ $pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
  {{- end }}
{{- end }}
