apiVersion: v1
kind: Secret
metadata:
  name: {{ template "management-portal.fullname" . }}-keystore
  labels:
{{ include "management-portal.labels" . | indent 4 }}
type: Opaque
data:
  keystore.p12: {{ .Values.keystore }}
