{{- if (include "management-portal.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "management-portal.fullname" . }}
  labels:
{{ include "management-portal.labels" . | indent 4 }}
type: Opaque
data:
  postgresql_password: {{ .Values.postgres.password | b64enc | quote }}
  managementportal_frontend_client_secret: {{ .Values.managementportal.frontend_client_secret | b64enc | quote }}
  managementportal_common_admin_password: {{ .Values.managementportal.common_admin_password | b64enc | quote }}
  {{- if and .Values.smtp.enabled .Values.smtp.auth }}
  smtpUsername: {{ .Values.smtp.username | b64enc | quote }}
  smtpPassword: {{ .Values.smtp.password | b64enc | quote }}
  {{ end }}
{{- end -}}
