{{- if .Values.postgres.ssl.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "management-portal.fullname" . }}-root-cert
  labels:
{{ include "management-portal.labels" . | indent 4 }}
type: Opaque
data:
  root.crt: {{ .Values.postgres.ssl.keystore }}
{{ end }}
