apiVersion: v2
appVersion: "3.2.0"
description: A Helm chart for the backend application of RADAR-base Appserver
name: radar-appserver
version: 0.0.1
sources: ["https://github.com/RADAR-base/RADAR-Appserver"]
deprecated: false
type: application
home: "https://radar-base.org"
maintainers:
  - email: yatharth.ranjan@kcl.ac.uk
    name: Yatharth Ranjan
    url: https://www.kcl.ac.uk/people/yatharth-ranjan
  - email: pauline.conde@kcl.ac.uk
    name: Pauline Conde
    url: https://www.kcl.ac.uk/people/pauline-conde
