apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "radar-self-enrolment-ui.fullname" . }}
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "radar-self-enrolment-ui.labels" . | nindent 4 }}
    {{- with .Values.deployment.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.deployment.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "radar-self-enrolment-ui.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "radar-self-enrolment-ui.labels" . | nindent 8 }}
        {{- with .Values.deployment.labels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.deployment.annotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      automountServiceAccountToken: {{ .Values.deployment.automountServiceAccountToken }}
      {{- with .Values.deployment.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.deployment.terminationGracePeriodSeconds }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: ORY_SDK_URL
            value: {{ .Values.kratosPublicUrl | quote }}
          - name: HYDRA_ADMIN_URL
            value: {{ .Values.hydraAdminUrl | quote }}
          - name: HYDRA_PUBLIC_URL
            value: {{ .Values.hydraPublicUrl | quote }}
          - name: PROJECT_NAME
            value: {{ .Values.projectName | quote }}
          - name: BASE_PATH
            value: {{ .Values.basePath | quote }}
          - name: JWKS_URL
            value: {{ .Values.jwksUrl | quote }}
          - name: SECURITY_MODE
            value: {{ .Values.securityMode | quote }}
          - name: COOKIE_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ include "radar-self-enrolment-ui.secretname" . }}
                key: secretsCookie
          - name: CSRF_COOKIE_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ include "radar-self-enrolment-ui.secretname" . }}
                key: secretsCSRFCookie
          - name: CSRF_COOKIE_NAME
            value: {{ .Values.config.csrfCookieName | quote }}
          {{- if .Values.deployment.extraEnv }}
            {{- toYaml .Values.deployment.extraEnv | nindent 10 }}
          {{- end }}
          {{- with .Values.deployment.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.basePath }}/health/alive
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.basePath }}/health/ready
              port: http
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
          {{- if .Values.securityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.deployment.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.deployment.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
