{{- if (include "radar-rest-sources-backend.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "radar-rest-sources-backend.fullname" . }}
  labels:
{{ include "radar-rest-sources-backend.labels" . | indent 4 }}
type: Opaque
data:
  postgresql_password: {{ .Values.postgres.password | b64enc | quote }}
{{- end -}}
