{{- if .Values.postgres.ssl.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "radar-rest-sources-backend.fullname" . }}-root-cert
  labels:
{{ include "radar-rest-sources-backend.labels" . | indent 4 }}
type: Opaque
data:
  root.crt: {{ .Files.Get "files/root.crt" | b64enc | quote }}
{{ end }}
