apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "radar-appserver.fullname" . }}
  labels:
{{ include "radar-appserver.labels" . | indent 4 }}
data:
  healthcheck.sh: |
    #!/bin/sh
    STATUS=$(curl -s --max-time 4 localhost:8080/actuator/health)
    if ! (echo "$STATUS" | grep -Fq 'db":{"status":"UP'); then
      exit 1
    fi
  radar_is.yml: |
    resourceName: {{ .Values.managementportal_resource_name }}

    # Set of supported public key endpoints for authentication
    publicKeyEndpoints:
        - https://{{ .Values.serverName }}/managementportal/oauth/token_key
        {{- range .Values.public_key_endpoints }}
        - {{ . | quote }}
        {{ end -}}

