apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "radar-appserver.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "radar-appserver.name" . }}
    helm.sh/chart: {{ include "radar-appserver.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "radar-appserver.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "radar-appserver.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: "app.kubernetes.io/name"
                    operator: In
                    values:
                    - {{ template "radar-appserver.name" . }}
                  - key: "app.kubernetes.io/instance"
                    operator: In
                    values:
                    - {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: RADAR_IS_CONFIG_LOCATION
            value: /etc/radar-appserver/radar_is.yml
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.database }}{{ .Values.postgres.connection_parameters }}"
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ template "radar-appserver.secretName" . }}
                key: databaseUser
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "radar-appserver.secretName" . }}
                key: databasePassword
          - name: SECURITY_RADAR_MANAGEMENTPORTAL_URL
            value: "http://{{ .Values.managementportal_host }}/managementportal"
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /etc/google/firebase-adminsdk.json
          - name: RADAR_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: {{ template "radar-appserver.secretName" . }}
                key: managementPortalClientId
          - name: RADAR_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "radar-appserver.secretName" . }}
                key: managementPortalClientSecret
          - name: SECURITY_GITHUB_CLIENT_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ template "radar-appserver.secretName" . }}
                key: githubClientToken
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - /etc/radar-appserver/healthcheck.sh
            failureThreshold: 3
            initialDelaySeconds: 20
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - /etc/radar-appserver/healthcheck.sh
            failureThreshold: 3
            initialDelaySeconds: 20
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/radar-appserver/
            - name: secrets
              mountPath: /etc/google/firebase-adminsdk.json
              subPath: firebaseAdminSdkKey
      volumes:
        - name: config
          configMap:
            name: {{ include "radar-appserver.fullname" . }}
        - name: secrets
          secret:
            secretName: {{ include "radar-appserver.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
