{{- if (include "radar-appserver.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "radar-appserver.fullname" . }}
  labels:
{{ include "radar-appserver.labels" . | indent 4 }}
type: Opaque
data:
  managementPortalClientId: {{ .Values.radar_admin_user | b64enc | quote }}
  managementPortalClientSecret: {{ .Values.radar_admin_password | b64enc | quote }}
  databaseUser: {{ .Values.postgres.user | b64enc | quote }}
  databasePassword: {{ .Values.postgres.password | b64enc | quote }}
  githubClientToken: {{ .Values.github_client_token | b64enc | quote }}
  firebaseAdminSdkKey: {{ .Values.google_application_credentials | b64enc | quote }}
  {{- if and .Values.smtp.enabled .Values.smtp.auth }}
  smtpUsername: {{ .Values.smtp.username | b64enc | quote }}
  smtpPassword: {{ .Values.smtp.password | b64enc | quote }}
  {{ end }}
{{- end -}}
