{{- if (include "radar-appserver.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "radar-appserver.fullname" . }}
  labels:
    app: {{ template "radar-appserver.name" . }}
    chart: {{ template "radar-appserver.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  managementPortalClientId: {{ .Values.radar_admin_user | b64enc | quote }}
  managementPortalClientSecret: {{ .Values.radar_admin_password | b64enc | quote }}
  databaseUser: {{ .Values.postgres.user | b64enc | quote }}
  databasePassword: {{ .Values.postgres.password | b64enc | quote }}
  githubClientToken: {{ .Values.github_client_token | b64enc | quote }}
  firebaseAdminSdkKey: {{ .Values.google_application_credentials | b64enc | quote }}
{{- end -}}
