{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "radar-push-endpoint.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "radar-push-endpoint.name" . }}
    helm.sh/chart: {{ include "radar-push-endpoint.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "radar-push-endpoint.name" . }}
      helm.sh/chart: {{ include "radar-push-endpoint.chart" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
  endpoints:
  - port: metrics
    interval: 15s
{{- end -}}