apiVersion: v1
kind: Service
metadata:
  name: {{ include "radar-push-endpoint.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "radar-push-endpoint.name" . }}
    helm.sh/chart: {{ include "radar-push-endpoint.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - name: metrics
      port: 5556
      protocol: TCP
      targetPort: metrics
  selector:
    app.kubernetes.io/name: {{ include "radar-push-endpoint.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
