# -- Number of cc-schema-registry-proxy replicas to deploy
replicaCount: 1

service:
  # -- Kubernetes Service type,
  type: ExternalName
  # -- Domain name used for pointing to actual schema registry instance
  externalName: schema-registry-domain
  # -- Port number to connect to Confluent platform
  port: 443

ingress:
  # -- Enable ingress controller resource
  enabled: true
  # -- Annotations that define default ingress class, certificate issuer
  # @default -- check values.yaml
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/preserve-host: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/backend-protocol: https
  # -- Path within the url structure
  path: "/schema/?(.*)"
  pathType: ImplementationSpecific
  # -- Hosts to accept requests from
  hosts:
    - localhost
  tls:
    # -- TLS Secret Name
    secretName: radar-base-tls

cc:
  # -- Confluent cloud schema registry API key
  schemaRegistryApiKey: srApiKey
  # -- Confluent cloud schema registry API secret
  schemaRegistryApiSecret: srApiSecret
