apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}-properties
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  source-fitbit.properties: |
    name=radar-fitbit-source
    connector.class=org.radarbase.connect.rest.fitbit.FitbitSourceConnector
    tasks.max={{ .Values.connector_num_tasks }}
    rest.source.base.url={{ .Values.fitbit_api_url }}
    rest.source.poll.interval.ms={{ .Values.rest_source_poll_interval_ms | int }}
    rest.source.request.generator.class=org.radarbase.connect.rest.fitbit.request.FitbitRequestGenerator
    fitbit.api.client={{ .Values.fitbit_api_client }}
    fitbit.api.secret={{ .Values.fitbit_api_secret }}
    fitbit.api.intraday={{ .Values.includeIntradayData }}
    fitbit.user.repository.class=org.radarbase.connect.rest.fitbit.user.{{ .Values.user_repository_class }}
    fitbit.user.repository.url={{ .Values.radar_rest_sources_backend_url }}
    fitbit.user.repository.client.id={{ .Values.oauthClientId }}
    fitbit.user.repository.client.secret={{ .Values.oauthClientSecret }}
    fitbit.user.repository.oauth2.token.url={{ .Values.auth_url }}
    fitbit.user.poll.interval={{ .Values.fitbit_user_poll_interval | int }}
    application.loop.interval.ms={{ .Values.application_loop_interval_ms | int }}
    user.cache.refresh.interval.ms={{ .Values.user_cache_refresh_interval_ms | int}}
    fitbit.intraday.steps.enabled={{ .Values.routes.intradaySteps.enabled }}
    fitbit.intraday.steps.topic={{ .Values.routes.intradaySteps.topic }}
    fitbit.intraday.heart.rate.enabled={{ .Values.routes.intradayHeartRate.enabled }}
    fitbit.intraday.heart.rate.topic={{ .Values.routes.intradayHeartRate.topic }}
    fitbit.intraday.heart.rate.variability.enabled={{ .Values.routes.intradayHeartRateVariability.enabled }}
    fitbit.intraday.heart.rate.variability.topic={{ .Values.routes.intradayHeartRateVariability.topic }}
    fitbit.resting.heart.rate.enabled={{ .Values.routes.restingHeartRate.enabled }}
    fitbit.resting.heart.rate.topic={{ .Values.routes.restingHeartRate.topic }}
    fitbit.sleep.stages.enabled={{ .Values.routes.sleepStages.enabled }}
    fitbit.sleep.stages.topic={{ .Values.routes.sleepStages.topic }}
    fitbit.sleep.classic.enabled={{ .Values.routes.sleepClassic.enabled }}
    fitbit.sleep.classic.topic={{ .Values.routes.sleepClassic.topic }}
    fitbit.timezone.enabled={{ .Values.routes.timezone.enabled }}
    fitbit.timezone.topic={{ .Values.routes.timezone.topic }}
    fitbit.activity.log.enabled={{ .Values.routes.activityLog.enabled }}
    fitbit.activity.log.topic={{ .Values.routes.activityLog.topic }}
    fitbit.intraday.calories.enabled={{ .Values.routes.intradayCalories.enabled }}
    fitbit.intraday.calories.topic={{ .Values.routes.intradayCalories.topic }}
    fitbit.intraday.spo2.enabled={{ .Values.routes.intradaySpo2.enabled }}
    fitbit.intraday.spo2.topic={{ .Values.routes.intradaySpo2.topic }}
    fitbit.breathing.rate.enabled={{ .Values.routes.breathingRate.enabled }}
    fitbit.breathing.rate.topic={{ .Values.routes.breathingRate.topic }}
    fitbit.skin.temperature.enabled={{ .Values.routes.skinTemperature.enabled }}
    fitbit.skin.temperature.topic={{ .Values.routes.skinTemperature.topic }}
  {{- if and .Values.kafka_wait.enabled .Values.kafka_wait.properties }}
  kafka-wait.properties: |
    {{ .Values.kafka_wait.properties | indent 4 }}
  {{- end }}
