apiVersion: v2
appVersion: "0.1.2"
description: RADAR-base home page.
name: radar-home
version: 0.1.1
sources: ["https://github.com/RADAR-base/radar-home"]
type: application
home: "https://radar-base.org"
maintainers:
  - email: keyvan@thehyve.nl
    name: Keyvan Hedayati
    url: https://www.thehyve.nl
  - email: joris@thehyve.nl
    name: Joris Borgdorff
    url: https://www.thehyve.nl/experts/joris-borgdorff
