name: Release Helm Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Add Helm repos
        run: |
          helm repo add jetstack https://charts.jetstack.io
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add vmware-tanzu https://vmware-tanzu.github.io/helm-charts

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        with:
          config: .github/cr.yaml
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Run chart-releaser -- order 0 external dependencies
        uses: helm/chart-releaser-action@v1.4.0
        with:
          config: .github/cr.yaml
          charts_dir: external
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Run chart-releaser -- order 2 external dependencies
        uses: helm/chart-releaser-action@v1.4.0
        with:
          config: .github/cr.yaml
          charts_dir: external/order-2
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
