name: Lint Charts

on:
  pull_request:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  helm-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch helm-docs
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: norwoodj/helm-docs
          version: "tags/v1.8.1"
          file: "helm-docs_1.8.1_Linux_x86_64.tar.gz"
          target: "helm-docs.tar.gz"

      - name: Run helm-docs
        run: |
          tar xzf helm-docs.tar.gz
          ./helm-docs -s file --template-files=charts/_templates.gotmpl --template-files=DOCS.md.gotmpl --template-files=README.md.gotmpl --chart-search-root=charts

      - name: Check helm docs did not change anything
        run: |
          CHANGES=$(git diff charts :^charts/kafka-manager)
          if [ -n "${CHANGES}" ]; then
            printf "README is not up to date with helm-docs. Following mismatches are detected:\n$CHANGES\n"
            exit 1
          fi
  
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1

      - name: Run chart-testing (lint)
        run: ct lint --config .github/ct-lint.yaml

  lint-artifacthub:
    runs-on: ubuntu-20.04
    container:
      image: artifacthub/ah
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Lint internal charts
        working-directory: ./charts/
        run: ah lint

      - name: Lint external charts
        working-directory: ./external/
        run: ah lint
  #
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #
  #     - name: Fetch history
  #       run: git fetch --prune --unshallow
  #
  #     - name: Set up chart-testing
  #       uses: helm/chart-testing-action@v2.1.0
  #
  #     - name: Create kind cluster
  #       uses: helm/kind-action@v1.2.0
  #
  #     - name: Run chart-testing (install)
  #       run: ct install --config .github/ct-install.yaml
