name: Pre-commit hooks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: read-all

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0
        with:
          enable-cache: 'true'

      - name: Run pre-commit on all files
        env:
          SKIP: "no-commit-to-branch"
        run: devbox run -- pre-commit run --verbose --all-files --show-diff-on-failure

  helm-deps-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Check Helm chart dependencies
        run: |
          for chart in charts/*; do
            if [[ -d "$chart" && -f "$chart/Chart.yaml" ]]; then
              echo "Checking dependencies for $chart"
              helm dependency build "$chart"
            fi
          done
