apiVersion: v1
kind: Secret
metadata:
  name: {{ template "s3-proxy.fullname" . }}
  labels:
{{ include "s3-proxy.labels" . | indent 4 }}
type: Opaque
data:
  s3Credential: {{ .Values.s3.credential | b64enc | quote }}
  targetCredential: {{ .Values.target.credential | b64enc | quote }}
